### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Cubixmeister** [Nathat23/StackMob-5#49]
How is this code licensed? Is it GPL?

My team would be happy to use it and contribute code if we could distribute binaries with our projects.

**Comment by Cubixmeister** [comment]
@Nathat23 ?

**Comment by Geolykt** [comment]
A year later I have a similar issue. Since there is no public maven repository (from my research of just looking at the README), I have to distribute it through my own maven repository, but that is not really possible due to the current license (also known as "all rights reserved").
This would all lead to compatibillity issues for the plugin, like with https://github.com/Geolykt/EnchantmentsPlus/issues/41 that can only be fixed inside a experimental branch that will not see the light of day otherwise as I still wish for my plugin to be buildable without any unnecessary dependencies that one needs to build beforehand

**Comment by Nathat23** [comment]
A license has been added.
